# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * base_exception
#
# Translators:
# OCA Transbot <transbot@odoo-community.org>, 2017
# enjolras <yo@miguelrevilla.com>, 2018
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 11.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-03-03 10:08+0000\n"
"PO-Revision-Date: 2018-03-03 10:08+0000\n"
"Last-Translator: enjolras <yo@miguelrevilla.com>, 2018\n"
"Language-Team: Spanish (https://www.transifex.com/oca/teams/23907/es/)\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_active
msgid "Active"
msgstr "Activo"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_model
msgid "Apply on"
msgstr "Aplicar en"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_create_uid
msgid "Created by"
msgstr "Creado por"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_create_date
msgid "Created on"
msgstr "Creado el"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_description
msgid "Description"
msgstr "Descripción"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_base_exception_display_name
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_confirm_display_name
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_display_name
msgid "Display Name"
msgstr "Nombre a mostrar"

#. module: base_exception
#: code:addons/base_exception/models/base_exception.py:215
#, python-format
msgid ""
"Error when evaluating the exception.rule rule:\n"
" %s \n"
"(%s)"
msgstr ""
"Error al evaluar la regla exception.rule:\n"
"%s\n"
"(%s)"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_name
msgid "Exception Name"
msgstr "Nombre de la excepción"

#. module: base_exception
#: model:ir.ui.view,arch_db:base_exception.view_exception_rule_tree
msgid "Exception Rule"
msgstr "Regla de excepción"

#. module: base_exception
#: model:ir.ui.view,arch_db:base_exception.view_exception_rule_form
msgid "Exception Rule Setup"
msgstr "Configuración de regla de excepción"

#. module: base_exception
#: model:ir.actions.act_window,name:base_exception.action_exception_rule_tree
#: model:ir.model,name:base_exception.model_exception_rule
#: model:ir.ui.menu,name:base_exception.menu_action_exception
msgid "Exception Rules"
msgstr "Reglas de excepción"

#. module: base_exception
#: model:res.groups,name:base_exception.group_exception_rule_manager
msgid "Exception manager"
msgstr "Administrador de excepciones"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_base_exception_exception_ids
msgid "Exceptions"
msgstr "Excepciones"

#. module: base_exception
#: model:ir.ui.view,arch_db:base_exception.view_exception_rule_confirm
msgid "Exceptions Rules"
msgstr "Reglas de excepción"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_confirm_exception_ids
msgid "Exceptions to resolve"
msgstr "Excepciones por resolver"

#. module: base_exception
#: model:ir.model.fields,help:base_exception.field_exception_rule_sequence
msgid "Gives the sequence order when applying the test"
msgstr ""

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_base_exception_id
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_confirm_id
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_id
msgid "ID"
msgstr "ID"

#. module: base_exception
#: model:ir.model.fields,help:base_exception.field_exception_rule_next_state
msgid ""
"If we detect exception we set the state of object (ex purchase) to the "
"next_state (ex 'to approve'). If there are more than one exception detected "
"and all have a value for next_state, we usethe exception having the smallest "
"sequence value"
msgstr ""

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_base_exception_ignore_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_confirm_ignore
msgid "Ignore Exceptions"
msgstr "Ignorar excepciones"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_base_exception___last_update
#: model:ir.model.fields,field_description:base_exception.field_exception_rule___last_update
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_confirm___last_update
msgid "Last Modified on"
msgstr "Última actualización por"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_write_uid
msgid "Last Updated by"
msgstr "Última actualización por"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_write_date
msgid "Last Updated on"
msgstr "Última actualización el"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_base_exception_main_exception_id
msgid "Main Exception"
msgstr "Excepción principal"

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_next_state
msgid "Next state"
msgstr "Estado siguiente"

#. module: base_exception
#: code:addons/base_exception/wizard/base_exception_confirm.py:28
#, python-format
msgid "Only 1 ID accepted, got %r."
msgstr ""

#. module: base_exception
#: model:ir.actions.act_window,name:base_exception.action_exception_rule_confirm
msgid "Outstanding exceptions to manage"
msgstr ""

#. module: base_exception
#: model:ir.ui.view,arch_db:base_exception.view_exception_rule_confirm
msgid "Outstanding exceptions to manager"
msgstr ""

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_code
msgid "Python Code"
msgstr "Código python"

#. module: base_exception
#: model:ir.model.fields,help:base_exception.field_exception_rule_code
msgid ""
"Python code executed to check if the exception apply or not. Use failed = "
"True to block the exception"
msgstr ""

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_confirm_related_model_id
msgid "Related Model"
msgstr ""

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_base_exception_rule_group
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_rule_group
msgid "Rule Group"
msgstr "Grupo de reglas"

#. module: base_exception
#: model:ir.model.fields,help:base_exception.field_exception_rule_rule_group
msgid ""
"Rule group is used to group the rules that must validated at same time for a "
"target object. Ex: validate sale.order.line rules with sale order rules."
msgstr ""

#. module: base_exception
#: model:ir.model.fields,field_description:base_exception.field_exception_rule_sequence
msgid "Sequence"
msgstr "Secuencia"

#. module: base_exception
#: code:addons/base_exception/models/base_exception.py:87
#, python-format
msgid ""
"The value \"%s\" you choose for the \"next state\" field state of \"%s\" is "
"wrong. Value must be in this list %s"
msgstr ""

#. module: base_exception
#: model:ir.ui.view,arch_db:base_exception.view_exception_rule_confirm
msgid "_Close"
msgstr ""

#. module: base_exception
#: model:ir.model,name:base_exception.model_base_exception
msgid "base.exception"
msgstr "base.exception"

#. module: base_exception
#: model:ir.model,name:base_exception.model_exception_rule_confirm
msgid "exception.rule.confirm"
msgstr "exception.rule.confirm"
