# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * auth_brute_force
# 
# Translators:
# OCA Transbot <transbot@odoo-community.org>, 2017
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 10.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2017-08-01 02:43+0000\n"
"PO-Revision-Date: 2017-08-01 02:43+0000\n"
"Last-Translator: OCA Transbot <transbot@odoo-community.org>, 2017\n"
"Language-Team: German (https://www.transifex.com/oca/teams/23907/de/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: de\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote_active
msgid "Active"
msgstr "Aktiv"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_attempt_date
msgid "Attempt Date"
msgstr "Versuchsdatum"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote_attempt_ids
msgid "Attempts"
msgstr "Anläufe"

#. module: auth_brute_force
#: model:ir.actions.act_window,name:auth_brute_force.action_res_authentication_attempt
#: model:ir.ui.menu,name:auth_brute_force.menu_res_authentication_attempt
msgid "Authentication Attempts"
msgstr "Authentifizierungsversuche"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_result
msgid "Authentication Result"
msgstr "Ergebnis der Authentifizierung"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote_ban_date
msgid "Ban Date"
msgstr "Sperrdatum"

#. module: auth_brute_force
#: code:addons/auth_brute_force/models/res_authentication_attempt.py:15
#: model:ir.ui.view,arch_db:auth_brute_force.view_res_authentication_attempt_search
#: selection:res.authentication.attempt,result:0
#, python-format
msgid "Banned"
msgstr "Gesperrt"

#. module: auth_brute_force
#: model:ir.actions.act_window,name:auth_brute_force.action_res_banned_remote
#: model:ir.ui.menu,name:auth_brute_force.menu_res_banned_remote
msgid "Banned Remotes"
msgstr "Gesperrte Remotes"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_create_uid
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote_create_uid
msgid "Created by"
msgstr "Erstellt von"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_create_date
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote_create_date
msgid "Created on"
msgstr "Erstellt am:"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote_description
msgid "Description"
msgstr "Beschreibung"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_display_name
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote_display_name
msgid "Display Name"
msgstr "Anzeigename"

#. module: auth_brute_force
#: code:addons/auth_brute_force/models/res_authentication_attempt.py:14
#: model:ir.ui.view,arch_db:auth_brute_force.view_res_authentication_attempt_search
#: selection:res.authentication.attempt,result:0
#, python-format
msgid "Failed"
msgstr "Gescheitert"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_id
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote_id
msgid "ID"
msgstr "ID"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt___last_update
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote___last_update
msgid "Last Modified on"
msgstr "Zuletzt geändert am"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_write_uid
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote_write_uid
msgid "Last Updated by"
msgstr "Zuletzt aktualisiert von"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_write_date
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote_write_date
msgid "Last Updated on"
msgstr "Zuletzt aktualisiert am"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_remote
#: model:ir.model.fields,field_description:auth_brute_force.field_res_banned_remote_remote
msgid "Remote ID"
msgstr "Ferne ID"

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.view_res_authentication_attempt_search
msgid "Successful"
msgstr "Erfolgreich"

#. module: auth_brute_force
#: code:addons/auth_brute_force/models/res_authentication_attempt.py:13
#: selection:res.authentication.attempt,result:0
#, python-format
msgid "Successfull"
msgstr "Erfolgreich"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_login
msgid "Tried Login"
msgstr "Versuchte Anmeldung"

#. module: auth_brute_force
#: model:ir.model.fields,help:auth_brute_force.field_res_banned_remote_active
msgid "Uncheck this box to unban the remote"
msgstr "Diese Box abwählen, um Fernnutzer zu entsperren"

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.view_res_authentication_attempt_search
msgid "Without Success"
msgstr "Erfolglos"

#. module: auth_brute_force
#: model:ir.model,name:auth_brute_force.model_res_authentication_attempt
msgid "res.authentication.attempt"
msgstr ""

#. module: auth_brute_force
#: model:ir.model,name:auth_brute_force.model_res_banned_remote
msgid "res.banned.remote"
msgstr ""
